In [1]:
import pandas as pd
import numpy as np
from manage_lop import Lop
from manage_db import Manage_db
import json
import os
import re
from manage_authentication import Authentication
import urllib3
import time
import warnings
warnings.filterwarnings('ignore')
urllib3.disable_warnings()
#import sklearn

In [2]:
#Lendo variáveis de ambiente para o postgree
PASSWORD_DB = 'senh@0'
USER_DB = 'postgres'
#Instanciando classes do postgree
lop = Lop()
psql = Manage_db(database = 'lop', host = 'localhost', port = '5432', 
                 user = USER_DB, password = PASSWORD_DB)
df_quest = psql.search(table='questions')
#df_class.loc[df['id_class'] == 'f2dd7bef-5b5d-4cb3-9efa-aa8652af0605']
id_class = 'e378c59f-e815-4a41-95fc-e95e4432a34c'
pd_data = pd.DataFrame([id_class], columns = ['id_class'])
condition = "WHERE id_class = 'e378c59f-e815-4a41-95fc-e95e4432a34c'"
df_submission = psql.search(table='submissions', condition=condition)
df_lop_lists = psql.search(table='lists', condition=condition)
df_lop_tests = psql.search(table='tests', condition=condition) 
df_class = psql.search(table='teachers_classes')
#nem todas as listas submetidas foram para fazer ou não foram submetidas pelos alunos

In [3]:
#aprovados - acima da media
#submissoes da turma
df_performance = df_submission.groupby(['user','registration','list','question'])['hitPercentage'].max().reset_index()
#soma das notas por lista
df_performance = df_performance.groupby(['user','registration','list'])['hitPercentage'].sum().reset_index()
#Me traz as porcentagens maximas de acerto por questão
df_performance = df_submission.groupby(['user','registration','list','question'])['hitPercentage'].max().reset_index()
      #Soma as porcentagens de uma lista/prova unica
df_performance = df_performance.groupby(['user','registration','list'])['hitPercentage'].sum().reset_index()
      #Renomeando para melhorar entendimento
df_performance.rename(columns={'hitPercentage':'totalHitPercentage'}, inplace = True)
#Listas cadastradas nessa turma
lists = df_lop_lists['list'].drop_duplicates().values
#Lista de alunos
df_without_duplicates = df_submission.drop_duplicates(subset=['registration'])
df_without_duplicates = df_without_duplicates[['user','registration']]
df_prov = pd.DataFrame()
for lista in lists:
    df_users = df_without_duplicates.copy()
    df_users['list'] = lista
    df_prov = df_prov.append(df_users)
df_prov
#df_prov.loc[df_prov['user']=='Flávio']
df_performance = pd.merge(df_performance,df_prov, on=['user','registration','list'], how='outer')#.fillna(0)  
df_question_data = df_quest.groupby(['list','question'])['id_list'].count().reset_index()
      #Conta quantas questões tem por lista
df_question_data = df_question_data.groupby(['list'])['question'].count().reset_index()
    #Renomeando lista
df_question_data.rename(columns={'question':'totalQuestionslist'}, inplace = True)
      #Merge
df_performance = df_performance.merge(df_question_data, on = 'list')
    #Média de acerto por lista
df_performance['medialist'] = df_performance['totalHitPercentage'] / df_performance['totalQuestionslist']
      #Convertendo para datetime
df_lop_lists['createdAt'] = pd.to_datetime(df_lop_lists['createdAt'])
      #Criando campo com a data
df_lop_lists['dateList'] = df_lop_lists['createdAt'].dt.date
      #Merge
#df_performance = pd.merge(df_performance, df_lop_lists.drop(columns = ['createdAt']), on='list')
#graph1
#Número de alunos na turma
#total_students = df_submission['registration'].drop_duplicates().count()
#Media por lista na turma
#df_mean_list = (df_performance.groupby(['list'])['medialist'].sum() / total_students).reset_index(name='mediaListClass')
#newDf = pd.merge(df_performance, df_mean_list,on=['list']).sort_values(by=['user','registration','dateList']).drop(columns = ['dateList', 'mediaListClass', 'id_list', 'shortTitle', 'totalHitPercentage', 'list', 'totalQuestionslist']).fillna(0)
    #newDf.loc[newDf['user']=='Alexandre Leonardo']
#newDf = newDf.groupby(['user','registration'])['medialist'].sum().reset_index()
#newDf['medialist'] = newDf['medialist'] / df_lop_lists.count().values[0]
    #newDf
    #newDf[newDf['medialist']>=50].values[0]
    #newDf['medialist'].values[0]
    #for a in range(newDf.count().values[0]):
    #    if newDf['medialist'].values[a]>=50:
    #        b=b+1
    #b
#newDf['aprovado'] = 2
#for a in range(newDf.count().values[0]):
#    if newDf['medialist'].values[a]>=50:
#        newDf['aprovado'][a]=1
#    else:
#        newDf['aprovado'][a]=0
#newDf[newDf['aprovado']==1]

In [4]:
#max de quantidade de questões enviadas e todo o tempo utilizado por questao 
#Convertendo para datetime
df_submission['createdAt'] = pd.to_datetime(df_submission['createdAt'])

    #Criando o campo de tempo em segundos, já que vem em ms
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)

    #Criando campo com a data
df_submission['dateSubmission'] = df_submission['createdAt'].dt.date

    #Dataframe sem duplicatas e com tempo maior que 0
df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','hitPercentage','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1).drop_duplicates()

    #Contando em quantos dias diferentes a questão foi submetida
df_user_days = df_without_duplicates.groupby(['registration','question','list'])['dateSubmission'].count().reset_index(name='differentDays')
      
    #Total de segundos gasto em cada questão por aluno
df_user_secounds = df_submission[df_submission["timeInSecounds"] > 0].groupby(['registration','question','list'])['timeInSecounds'].sum().reset_index(name='totalSecounds')

    #Descobrindo o tempo que cada questão levou para ser resolvida     
df_total_questions = df_submission[df_submission["timeInSecounds"] > 0].groupby(['registration','question','list'])['question'].count().reset_index(name='quantity')

    #Unindo em matrícula, questão e lista
df_user_secounds_days = pd.merge(df_user_secounds, df_total_questions, on=['registration','question','list'], how='outer')
    
    #Adicionando o campo nome
df_user_secounds_days = pd.merge(df_user_secounds_days, df_submission[['user','registration']].drop_duplicates(), on='registration', how='outer')
    
    #Retornando json
df_user_secounds_days

#observar a media de tempo por cada questao/lista

,registration,question,list,totalSecounds,quantity,user
0,2015002408,A média de 4 alunos,Repetição condicional - Lista Resolvida (LOP),39,5,margareth
1,2015002408,Calculando expressões - parte 1,Laboratório 01 - Expressões Aritméticas,13,1,margareth
2,2015002408,Calculando expressões - parte 2,Laboratório 01 - Expressões Aritméticas,3,1,margareth
3,2015002408,Calculando expressões - parte 3,Laboratório 01 - Expressões Aritméticas,3,1,margareth
4,2015002408,Calculando expressões - parte 4,Laboratório 01 - Expressões Aritméticas,149,4,margareth
...,...,...,...,...,...,...
5716,20200083109,Troca de dígitos UCD,Treinamento - Expressões Aritméticas,449,3,ANDERSON DOS ANJOS
5717,20200083109,Troca de dígitos UDC,Treinamento - Expressões Aritméticas,202,1,ANDERSON DOS ANJOS
5718,20200083109,Área e Volume do círculo de raio R,Aula - Funções Aritméticas,455,2,ANDERSON DOS ANJOS
5719,20200083109,É preciso praticar muito!,Laboratório 01 - Expressões Aritméticas,129,1,ANDERSON DOS ANJOS
5720,20200083109,Índice de Massa Corporal (IMC) - parte 2,Laboratório 02 - Estrutura de decisão,370,1,ANDERSON DOS ANJOS

In [5]:
#obs
#contando o erro por questao acima do tempo zero para prevenir duplo clicke. geralmente, se há cola ou algum problema relacionado, acaba nao sendo um erro na questao
#buscando erros por questao, por aluno
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)
df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1)
df_performance = df_without_duplicates[df_without_duplicates["hitPercentage"] == 0]
df_performance = df_performance.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalError')
df_performance

,user,registration,list,question,totalError
0,ANDERSON DOS ANJOS,20200083109,(Lop) Estruturas de decisão - problemas sobre ...,Calculando um ano bissexto.,2
1,ANDERSON DOS ANJOS,20200083109,(Lop) Estruturas de decisão - problemas sobre ...,Divisível por 3 e por 5,2
2,ANDERSON DOS ANJOS,20200083109,(Lop) Estruturas de decisão - problemas sobre ...,Divisível por 3 valores ao mesmo tempo,3
3,ANDERSON DOS ANJOS,20200083109,Aula - Funções Aritméticas,Calculo de expressão com expoente,1
4,ANDERSON DOS ANJOS,20200083109,Aula - Funções Aritméticas,Comissão do garçom no restaurante,1
...,...,...,...,...,...
3267,ursula,20190010621,Treinamento - Expressões Aritméticas,Troca de valores entre variáveis,9
3268,Ítalo,20190074173,Aula - Funções Aritméticas,Resto da divisão inteira,10
3269,Ítalo,20190074173,Aula - Introdução Expressões Aritiméticas,Raízes de uma equação de segundo grau,4
3270,Ítalo,20190074173,Laboratório 01 - Expressões Aritméticas,Cálculo do IMC,10
3271,Ítalo,20190074173,Laboratório 01 - Expressões Aritméticas,Imprimindo uma mensagem com um valor,8

In [6]:
#obs
#por aluno, buscando erro por assunto
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)
df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1).drop_duplicates()
df_performance = df_without_duplicates[df_without_duplicates["hitPercentage"] == 0]
df_performance = pd.merge(df_performance, df_quest[['list', 'question', 'tag1', 'tag2']].drop_duplicates(), on=['question','list'], how='outer')
df_performance['tag1'] = df_performance['tag1'].fillna('Assunto em Branco')
df_performance['tag2'] = df_performance['tag2'].fillna('Assunto em Branco')
df_performance = df_performance.drop(columns = ['question', 'list'])
df_performance1 = df_performance[df_performance["hitPercentage"] == 0].groupby(['user','registration', 'tag1'])['hitPercentage'].count().reset_index(name='totalErrorTag1')
df_performance2 = df_performance[df_performance["hitPercentage"] == 0].groupby(['user','registration', 'tag2'])['hitPercentage'].count().reset_index(name='totalErrorTag2')
df_performance = pd.merge(df_performance1, df_performance2, on=['user', 'registration'], how='outer')
df_performance
#quando houverem assuntos com nomes diferentes, o ideal é buscá-los por tag1 e tag2, juntar ambas tags numa só e verificar os assuntos iguais para haver os erros em conjunto
#problema no que foi falado anteriormente -> será contabilizado o mesmo erro 2x, mas 1x para cada assunto de uma mesma questão com mais de um assunto
#a forma que este dataframe atual está exposto, mostra a quantidade de erros total

,user,registration,tag1,totalErrorTag1,tag2,totalErrorTag2
0,ANDERSON DOS ANJOS,20200083109,Assunto em Branco,13,Assunto em Branco,13
1,Adriano dos Santos Silva,20200068766,Assunto em Branco,17,Assunto em Branco,17
2,Alessandro Rodrigues de Pontes,20190056498,Assunto em Branco,16,Assunto em Branco,16
3,Alexandre,20170115840,Assunto em Branco,39,Assunto em Branco,39
4,Alisson David,20180042210,Assunto em Branco,13,Assunto em Branco,13
...,...,...,...,...,...,...
150,pedrolucasdiniz,20190074370,Assunto em Branco,21,Assunto em Branco,21
151,rayanigomes,20190154855,Assunto em Branco,41,Assunto em Branco,41
152,rillary oliveira,20190156359,Assunto em Branco,36,Assunto em Branco,36
153,ursula,20190010621,Assunto em Branco,38,Assunto em Branco,38
154,Ítalo,20190074173,Assunto em Branco,4,Assunto em Branco,4

In [7]:
#df_class[df_class['id_class']=='e378c59f-e815-4a41-95fc-e95e4432a34c']
#175 alunos
#4 profs
#df_submission['registration'].drop_duplicates()
#156 registros
#df_submission['user'].drop_duplicates()
#153
a = df_class[df_class['id_class']=='e378c59f-e815-4a41-95fc-e95e4432a34c']
c = a['studentsCount'].iloc[0] - df_submission['registration'].drop_duplicates().count()
#não tem como descobrir o nome dos alunos que nunca submeteram algo
c

19.0

In [8]:
#buscando quantidade de alunos que não fizerem a questão
a = df_submission['question'].drop_duplicates().reset_index()
a = a.drop(['index'], axis=1)
f = df_class[df_class['id_class']=='e378c59f-e815-4a41-95fc-e95e4432a34c']
qtd_estudantes = f['studentsCount'].iloc[0]
df_without_duplicates = df_submission.drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number', 'user', 'test', 'registration', 'dateSubmission', 'id_class', 'language', 'hitPercentage'], axis=1).drop_duplicates().reset_index()
df_without_duplicates = df_without_duplicates.drop(['index'], axis=1)
df_without_duplicates['qtd_faltosos'] = 0
d= []
for i in range(len(a)):
    b = df_submission[df_submission['question']==a['question'][i]]
    #b = df_submission[df_submission['question']==a[0]]
    c = b['registration'].drop_duplicates().count()
    c = qtd_estudantes - c
    df_without_duplicates['qtd_faltosos'][i] = c
df_without_duplicates

,question,list,qtd_faltosos
0,Calcular expressões,Treinamento - Expressões Aritméticas,106
1,Troca de dígitos UCD,Treinamento - Expressões Aritméticas,99
2,Conversão de Temperatura entre paises,(Lop) Estruturas de decisão - Operadores Lógicos,98
3,Troca de dígitos UDC,Treinamento - Expressões Aritméticas,104
4,Altura acima de média,Laboratório 02 - Estrutura de decisão,95
...,...,...,...
84,Aprendendo a somar,Repetição condicional - Lista de Exercícios (LOP),107
85,Cálculo da média válida,Repetição condicional - Lista de Exercícios (LOP),119
86,Crescimento populacional,Repetição condicional - Lista de Exercícios (LOP),117
87,Tempo de vida de um material radioativo,Repetição condicional - Lista de Exercícios (LOP),126
88,Soma dos pares e ímpares digitados,Repetição condicional - Lista de Exercícios (LOP),119

In [9]:
#df = df_submission.drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1).drop_duplicates()
#df_performance = df.groupby(['user','registration','list','question'])['hitPercentage'].max().reset_index()

#salvando o nome das questoes
a = df_submission['question'].drop_duplicates().reset_index()
a = a.drop(['index'], axis=1)
#verificando q auntidade total de alunos na turma
f = df_class[df_class['id_class']=='e378c59f-e815-4a41-95fc-e95e4432a34c']
qtd_estudantes = f['studentsCount'].iloc[0]
#formando a tabela com nome de questoes para cada lista e adicionando a tabela para as faltas
df_without_duplicates = df_submission.drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number', 'user', 'test', 'registration', 'dateSubmission', 'id_class', 'language', 'hitPercentage'], axis=1).drop_duplicates().reset_index()
df_without_duplicates = df_without_duplicates.drop(['index'], axis=1)
df_without_duplicates['qtd_faltosos'] = 0
#laço para inserir a quantidade de alunos faltosos por questao
for i in range(len(a)):
    b = df_submission[df_submission['question']==a['question'][i]]
    c = b['registration'].drop_duplicates().count()
    c = qtd_estudantes - c
    df_without_duplicates['qtd_faltosos'][i] = c
#formando a tabela com nome de questoes para cada lista, adicionando a tabela que irá indicar a quantidade de alunos que ficaram acima/abaixo da media
df = df_submission.drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number', 'user', 'test', 'registration', 'dateSubmission', 'id_class', 'language', 'hitPercentage'], axis=1).drop_duplicates().reset_index()
df = df.drop(['index'], axis=1)
df['more'] = 0
df['less'] = 0
#laço para inserção dos valores de alunos acima/abaixo da media por queustao em cada lista
for i in range(len(a)):
    b = df_submission[df_submission['question']==a['question'][i]]
    d = b.groupby(['user','registration','list','question'])['hitPercentage'].max().reset_index()
    more = d[d['hitPercentage']>=70].count()
    less = d[d['hitPercentage']<70].count()
    df['more'][i]=more[0]
    df['less'][i]=less[0]
#junção da tabela com os dados de faltosos com a que contem os dados de alunos acima/abaixo da media
df = pd.merge(df, df_without_duplicates, on=['question', 'list'])
df

,question,list,more,less,qtd_faltosos
0,Calcular expressões,Treinamento - Expressões Aritméticas,59,10,106
1,Troca de dígitos UCD,Treinamento - Expressões Aritméticas,69,7,99
2,Conversão de Temperatura entre paises,(Lop) Estruturas de decisão - Operadores Lógicos,75,2,98
3,Troca de dígitos UDC,Treinamento - Expressões Aritméticas,60,11,104
4,Altura acima de média,Laboratório 02 - Estrutura de decisão,76,4,95
...,...,...,...,...,...
84,Aprendendo a somar,Repetição condicional - Lista de Exercícios (LOP),63,5,107
85,Cálculo da média válida,Repetição condicional - Lista de Exercícios (LOP),49,7,119
86,Crescimento populacional,Repetição condicional - Lista de Exercícios (LOP),52,6,117
87,Tempo de vida de um material radioativo,Repetição condicional - Lista de Exercícios (LOP),46,3,126
88,Soma dos pares e ímpares digitados,Repetição condicional - Lista de Exercícios (LOP),54,2,119

In [10]:
#por aluno (indicando qual foi o aluno), quantas questões não foram feitas/faltas
df_without_duplicates = df_submission.drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number', 'language', 'hitPercentage', 'dateSubmission', 'id_class', 'test'], axis=1).drop_duplicates()
df_without_duplicates = df_without_duplicates.groupby(['user','registration'])['question'].count().reset_index(name='porcent_questoes_feitas')
a = df_submission['question'].drop_duplicates().count()

porcent = []
for i in range(df_without_duplicates.count().values[0]):
    porcent.append((df_without_duplicates['porcent_questoes_feitas'][i] * 100)/a)
    df_without_duplicates['porcent_questoes_feitas'][i] = int(porcent[i])
df_without_duplicates = pd.merge(df_without_duplicates, newDf, on=['user', 'registration'], how='outer')
df_without_duplicates

,user,registration,porcent_questoes_feitas,medialist,aprovado
0,ANDERSON DOS ANJOS,20200083109,40,23.702063,0
1,Adriano dos Santos Silva,20200068766,24,14.551821,0
2,Alessandro Rodrigues de Pontes,20190056498,42,23.975045,0
3,Alexandre,20170115840,67,42.016807,0
4,Alisson David,20180042210,52,33.520321,0
...,...,...,...,...,...
151,pedrolucasdiniz,20190074370,33,23.758594,0
152,rayanigomes,20190154855,75,49.038282,0
153,rillary oliveira,20190156359,60,36.161905,0
154,ursula,20190010621,49,29.537815,0
155,Ítalo,20190074173,5,4.369748,0

In [11]:
#dos que acertaram/erraram a questao/lista, quantos foram aprovados
#obs
#contando o erro por questao acima do tempo zero para prevenir duplo clicke. geralmente, se há cola ou algum problema relacionado, acaba nao sendo um erro na questao
#buscando erros por questao, por aluno
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)
df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1)
df_erro = df_without_duplicates[df_without_duplicates["hitPercentage"] == 0]
df_erro = df_erro.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalError')

df_acerto = df_without_duplicates[df_without_duplicates["hitPercentage"] > 0]
df_acerto = df_acerto.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalAcert')

df_100 = df_without_duplicates[df_without_duplicates["hitPercentage"] == 100].drop_duplicates()
df_100 = df_100.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='acert_100')

#buscar se o aluno chegou a tirar 100 na questão ou a nota final.
#há mais de um acerto, pois há mais vezes que tentam tirar mais que zero, mas nem sempre chegam no 100
#avaliar a possibilidade de colocar a nota maxima do aluno em coluna
df = pd.merge(df_erro, df_acerto, on=['user', 'registration', 'list', 'question'], how='outer')
df = pd.merge(df, df_100, on=['user', 'registration', 'list', 'question'], how='outer')
df.replace(np.NaN, 0, inplace = True)
df = pd.merge(df, newDf, on=['user', 'registration']).drop('medialist', axis=1)
df

,user,registration,list,question,totalError,totalAcert,acert_100,aprovado
0,ANDERSON DOS ANJOS,20200083109,(Lop) Estruturas de decisão - problemas sobre ...,Calculando um ano bissexto.,2.0,9.0,0.0,0
1,ANDERSON DOS ANJOS,20200083109,(Lop) Estruturas de decisão - problemas sobre ...,Divisível por 3 e por 5,2.0,2.0,1.0,0
2,ANDERSON DOS ANJOS,20200083109,(Lop) Estruturas de decisão - problemas sobre ...,Divisível por 3 valores ao mesmo tempo,3.0,2.0,1.0,0
3,ANDERSON DOS ANJOS,20200083109,Aula - Funções Aritméticas,Calculo de expressão com expoente,1.0,1.0,1.0,0
4,ANDERSON DOS ANJOS,20200083109,Aula - Funções Aritméticas,Comissão do garçom no restaurante,1.0,0.0,0.0,0
...,...,...,...,...,...,...,...,...
5716,Ítalo,20190074173,Laboratório 01 - Expressões Aritméticas,Cálculo do IMC,10.0,4.0,1.0,0
5717,Ítalo,20190074173,Laboratório 01 - Expressões Aritméticas,Imprimindo uma mensagem com um valor,8.0,2.0,1.0,0
5718,Ítalo,20190074173,Aula - Introdução Expressões Aritiméticas,Fórmula de Bháskara,0.0,1.0,1.0,0
5719,Eline Rodrigues Ribeiro,20170043151,Treinamento - Expressões Aritméticas,Calcular expressões,0.0,1.0,1.0,0
5720,Eline Rodrigues Ribeiro,20170043151,Treinamento - Expressões Aritméticas,Troca de dígitos UCD,0.0,1.0,1.0,0

In [19]:
#contando o erro por questao acima do tempo zero para prevenir duplo clicke. geralmente, se há cola ou algum problema relacionado, acaba nao sendo um erro na questao
#buscando erros por questao, por aluno
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)
df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1)
df_erro = df_without_duplicates[df_without_duplicates["hitPercentage"] == 0]
df_erro = df_erro.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalError')
df_erro = df_erro.groupby(['user','registration','list'])['totalError'].sum()

df_acerto = df_without_duplicates[df_without_duplicates["hitPercentage"] > 0]
df_acerto = df_acerto.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalAcert')
df_acerto = df_acerto.groupby(['user','registration','list'])['totalAcert'].sum()

df_100 = df_without_duplicates[df_without_duplicates["hitPercentage"] == 100].drop_duplicates()
df_100 = df_100.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='acert_100')
df_100 = df_100.groupby(['user','registration','list'])['acert_100'].sum()

#buscar se o aluno chegou a tirar 100 na questão ou a nota final.
#há mais de um acerto, pois há mais vezes que tentam tirar mais que zero, mas nem sempre chegam no 100
#avaliar a possibilidade de colocar a nota maxima do aluno em coluna
df = pd.merge(df_erro, df_acerto, on=['user', 'registration', 'list'], how='outer')
df = pd.merge(df, df_100, on=['user', 'registration', 'list'], how='outer')
df.replace(np.NaN, 0, inplace = True)
#df = pd.merge(df, newDf, on=['user', 'registration']).drop('medialist', axis=1)
df
#adicionar a quantidade de questoes nao feitas

                                                                                          totalError  \
user                     registration list
ANDERSON DOS ANJOS       20200083109  (Lop) Estruturas de decisão - problemas sobre d...         7.0
                                      Aula - Funções Aritméticas                                 3.0
                                      Laboratório 02 - Estrutura de decisão                      7.0
                                      Treinamento - Expressões Aritméticas                      11.0
Adriano dos Santos Silva 20200068766  (Lop) Estruturas de decisão - problemas sobre d...        69.0
...                                                                                              ...
margareth                2015002408   Repetição condicional - Lista Resolvida (LOP)              0.0
                                      Treinamento - Expressões Aritméticas                       0.0
rayanigomes              20190154855  Laboratório 02 - Estrutura de decisão                      0.0
ursula                   20190010621  Aula - Introdução Expressões Aritiméticas                  0.0
                                      Laboratório 01 - Expressões Aritméticas                    0.0

                                                                                          totalAcert  \
user                     registration list
ANDERSON DOS ANJOS       20200083109  (Lop) Estruturas de decisão - problemas sobre d...        18.0
                                      Aula - Funções Aritméticas                                 6.0
                                      Laboratório 02 - Estrutura de decisão                     21.0
                                      Treinamento - Expressões Aritméticas                       6.0
Adriano dos Santos Silva 20200068766  (Lop) Estruturas de decisão - problemas sobre d...        38.0
...                                                                                              ...
margareth                2015002408   Repetição condicional - Lista Resolvida (LOP)             17.0
                                      Treinamento - Expressões Aritméticas                      13.0
rayanigomes              20190154855  Laboratório 02 - Estrutura de decisão                      4.0
ursula                   20190010621  Aula - Introdução Expressões Aritiméticas                  5.0
                                      Laboratório 01 - Expressões Aritméticas                    1.0

                                                                                          acert_100
user                     registration list
ANDERSON DOS ANJOS       20200083109  (Lop) Estruturas de decisão - problemas sobre d...        7.0
                                      Aula - Funções Aritméticas                                6.0
                                      Laboratório 02 - Estrutura de decisão                     8.0
                                      Treinamento - Expressões Aritméticas                      5.0
Adriano dos Santos Silva 20200068766  (Lop) Estruturas de decisão - problemas sobre d...        2.0
...                                                                                             ...
margareth                2015002408   Repetição condicional - Lista Resolvida (LOP)             4.0
                                      Treinamento - Expressões Aritméticas                      6.0
rayanigomes              20190154855  Laboratório 02 - Estrutura de decisão                     2.0
ursula                   20190010621  Aula - Introdução Expressões Aritiméticas                 2.0
                                      Laboratório 01 - Expressões Aritméticas                   1.0

[978 rows x 3 columns]

In [30]:
#contando o erro por questao acima do tempo zero para prevenir duplo clicke. geralmente, se há cola ou algum problema relacionado, acaba nao sendo um erro na questao
#buscando erros por questao, por aluno
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)
df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1)
df_erro = df_without_duplicates[df_without_duplicates["hitPercentage"] == 0]
df_erro = df_erro.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalError')
df_erro1 = df_erro.groupby(['user','registration','list'])['totalError'].sum()

df_acerto = df_without_duplicates[df_without_duplicates["hitPercentage"] > 0]
df_acerto = df_acerto.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalAcert')
df_acerto1 = df_acerto.groupby(['user','registration','list'])['totalAcert'].sum()

df_100 = df_without_duplicates[df_without_duplicates["hitPercentage"] == 100].drop_duplicates()
df_100 = df_100.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='acert_100')
df_100 = df_100.groupby(['user','registration','list'])['acert_100'].sum()

df_qtdqt = df_without_duplicates.drop(['language', 'hitPercentage', 'user', 'registration', 'test', 'dateSubmission', 'id_class'], axis=1).drop_duplicates()
df_qtdqt = df_qtdqt.groupby(['list'])['question'].count().reset_index(name='qtd_quest')

df_erro_acert = pd.merge(df_erro, df_acerto, on=['user', 'registration', 'list', 'question'], how='outer')
df_erro_acert.replace(np.NaN, 0, inplace = True)

df_qtdqa = df_erro_acert.groupby(['user', 'registration', 'list'])['question'].count().reset_index(name='qtd_quest')

#buscar se o aluno chegou a tirar 100 na questão ou a nota final.
#há mais de um acerto, pois há mais vezes que tentam tirar mais que zero, mas nem sempre chegam no 100
#avaliar a possibilidade de colocar a nota maxima do aluno em coluna
df = pd.merge(df_erro, df_acerto, on=['user', 'registration', 'list', 'question'], how='outer')
df1 = pd.merge(df, df_100, on=['user', 'registration', 'list'], how='outer')
df1.replace(np.NaN, 0, inplace = True)
#nao está inserindo a list, pq nao consta ela como coluna de df
#df = pd.merge(df, newDf, on=['user', 'registration']).drop('medialist', axis=1)

type(df_acerto)

#adicionar a quantidade de questoes nao feitas
#media com questoes feitas e media com numero total de questoes da lista

pandas.core.frame.DataFrame

In [14]:
#contando o erro por questao acima do tempo zero para prevenir duplo clicke. geralmente, se há cola ou algum problema relacionado, acaba nao sendo um erro na questao
#buscando erros por lista, por aluno
df_submission['timeInSecounds'] = df_submission['timeConsuming'].divide(1000).astype(int)

df_without_duplicates = df_submission[df_submission["timeInSecounds"] > 0].drop(['environment','timeConsuming','createdAt','timeInSecounds','char_change_number'], axis=1)
df_erro = df_without_duplicates[df_without_duplicates["hitPercentage"] == 0]
df_erro = df_erro.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalError')
df_erro = df_erro.groupby(['user','registration'])['totalError'].sum()

#buscando quantidade de questoes certas por lista por aluno
df_acerto = df_without_duplicates[df_without_duplicates["hitPercentage"] > 0]
df_acerto = df_acerto.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='totalAcert')
df_acerto = df_acerto.groupby(['user','registration'])['totalAcert'].sum()

#buscando quantidade de questoes que com 100% de acerto por lista por aluno
df_100 = df_without_duplicates[df_without_duplicates["hitPercentage"] == 100].drop_duplicates()
df_100 = df_100.groupby(['user','registration','list','question'])['hitPercentage'].count().reset_index(name='acert_100')
df_100 = df_100.groupby(['user','registration'])['acert_100'].sum()

#buscar se o aluno chegou a tirar 100 na questão ou a nota final.
#há mais de um acerto, pois há mais vezes que tentam tirar mais que zero, mas nem sempre chegam no 100
#avaliar a possibilidade de colocar a nota maxima do aluno em coluna
df = pd.merge(df_erro, df_acerto, on=['user', 'registration'], how='outer')
df = pd.merge(df, df_100, on=['user', 'registration'], how='outer')
df.replace(np.NaN, 0, inplace = True)
df = pd.merge(df, newDf, on=['user', 'registration']).drop('medialist', axis=1)
df
#adicionar a quantidade de listas feitas e nao feitas
#adicionar a quantidade de quest feitas e nao feitas
#verificar a quantidade de submissoes por aluno

#observar que a quantidade de questoes tiradas 100, estao dentro da quantidade de questoes acertadas, pois as acertadas tambem contem as notas 100
#alunos que nao tiveram questoes erradas, podem ter feito a questao em um compilador/ide externo

,user,registration,totalError,totalAcert,acert_100,aprovado
0,ANDERSON DOS ANJOS,20200083109,28.0,58.0,33.0,0
1,Adriano dos Santos Silva,20200068766,195.0,67.0,20.0,0
2,Alessandro Rodrigues de Pontes,20190056498,32.0,120.0,37.0,0
3,Alexandre,20170115840,181.0,118.0,60.0,0
4,Alisson David,20180042210,26.0,54.0,43.0,0
...,...,...,...,...,...,...
151,rayanigomes,20190154855,357.0,189.0,70.0,0
152,rillary oliveira,20190156359,262.0,123.0,53.0,0
153,ursula,20190010621,250.0,78.0,43.0,0
154,Ítalo,20190074173,32.0,13.0,5.0,0
155,Eline Rodrigues Ribeiro,20170043151,0.0,2.0,2.0,0